name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Documentation
      run: cargo doc --verbose
    - name: Formatting
      run: cargo fmt -- --check
    - uses: giraffate/clippy-action@v1
      with:
        clippy_flags: -- -D warnings
        reporter: github-pr-review
